---
- hosts: all
  become: true
  vars_files:
    - variables.yaml

  roles:
    - 0_Setting_up_Passwordless_SSH
    - 1_Installing_Security_Updates
    - 2.1_Installing_crucial _System_Packages
    - 2.2_Installing_helpful_System_Packages
    - 4_Grabbing_and_PreProcessing_Extracts
    - 5_Starting_APP_Server
    