---
- 
    - name: Updating apt-cache 
      apt: update_cache=yes
      sudo: yes

    - name: Installing Crucial System Packages and OSRM Dependencies
      apt: pkg={{ item }} state=latest update-cache=yes
      sudo: yes
      with_items:
        - git
        - python-dev
        - gcc
        - python-setuptools   
        - build-essential
        - cmake
        - pkg-config
        - libbz2-dev
        - libstxxl-dev
        - libstxxl1v5
        - libxml2-dev
        - libzip-dev
        - libboost-all-dev
        - lua5.2
        - liblua5.2-dev
        - libtbb-dev
