---
- 
    - name: Grab a .osm.pbf extract from Geofabrik or Mapzen's Metro Extracts
      get_url: url=http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf dest=/opt/OSRM/berlin-latest.osm.pbf


    - name: Pre-process the extract
      sudo: yes
      command: chdir=/opt/OSRM/ {{ item }}
      with_items:
        - osrm-extract berlin-latest.osm.pbf -p profiles/car.lua
        - osrm-contract berlin-latest.osrm        